#!/bin/bash

# Simple test script for OWR routing fixes
# Run this script in one terminal; it will guide you through testing in multiple terminals.

echo "=== OWR Routing Test Script ==="
echo "This script tests the fixes: no self-route broadcast, proper route addition, state initialization, and full routing table display."
echo ""
echo "Open 3 terminals:"
echo "Terminal 1: Node 60 (port 60060)"
echo "Terminal 2: Node 61 (port 60061)"
echo "Terminal 3: Node 62 (port 60062)"
echo ""
echo "=== PHASE 1: Start Nodes ==="
echo "In Terminal 1: ./owr 127.0.0.1 60060"
echo "Type: dj 100 60"
echo "Type: sm  (enable monitor)"
echo ""
echo "In Terminal 2: ./owr 127.0.0.1 60061"
echo "Type: dj 100 61"
echo "Type: sm"
echo ""
echo "In Terminal 3: ./owr 127.0.0.1 60062"
echo "Type: dj 100 62"
echo "Type: sm"
echo ""
echo "=== PHASE 2: Connect Nodes (Linear: 60 -> 61 -> 62) ==="
echo "In Terminal 1 (Node 60): dae 61 127.0.0.1 60061"
echo "In Terminal 2 (Node 61): dae 60 127.0.0.1 60060"
echo "In Terminal 2 (Node 61): dae 62 127.0.0.1 60062"
echo "In Terminal 3 (Node 62): dae 61 127.0.0.1 60061"
echo ""
echo "=== PHASE 3: Announce and Check Routes ==="
echo "In Terminal 1 (Node 60): a  (announce - should not broadcast self-route)"
echo "In Terminal 1: sr  (show all routes - should include self cost 0, and propagated routes)"
echo "In Terminal 2: a"
echo "In Terminal 2: sr"
echo "In Terminal 3: a"
echo "In Terminal 3: sr"
echo ""
echo "Expected: Routes propagate (e.g., 60 knows 62 via 61), no self-broadcast in monitor, states are EXPEDITION/COORDINATION correctly."
echo ""
echo "=== PHASE 4: Test Messages ==="
echo "In Terminal 1 (Node 60): m 62 hello"
echo "Check Terminal 3 for received message."
echo ""
echo "=== PHASE 5: Check Monitor Logs ==="
echo "After testing: cat /tmp/owr_monitor.log"
echo "Verify no 'Broadcast ROUTE XX cost=0' for self, and proper route updates."
echo ""
echo "=== Cleanup ==="
echo "In each terminal: l  (leave network)"
echo "Kill processes if needed: pkill -f owr"
echo ""
echo "Run this script to see the guide, then follow in terminals."